=== kunishi/chorusroom-cms/lib/dtd/jca-comp-result.dtd
<!-- Generated by Relaxer 0.16.1 -->
<!-- Fri Aug 23 00:20:09 GMT-09:00 2002 -->

<!ELEMENT reporter-name (#PCDATA | cr:utf8-char)*>
<!ATTLIST reporter-name xml:lang CDATA #IMPLIED>
<!ATTLIST reporter-name penname CDATA #IMPLIED>

<!ELEMENT program (given-program?, free-program+)>

<!ELEMENT accompaniment (#PCDATA | cr:utf8-char)*>
<!ATTLIST accompaniment xml:lang CDATA #IMPLIED>
<!ATTLIST accompaniment instrument CDATA #REQUIRED>

<!ELEMENT score (#PCDATA)>
<!ATTLIST score referee CDATA #REQUIRED>

<!ELEMENT hall (#PCDATA | cr:utf8-char)*>

<!ELEMENT p:originated-from (#PCDATA | cr:utf8-char)*>
<!ATTLIST p:originated-from xml:lang CDATA #IMPLIED>

<!ELEMENT startTime (#PCDATA)>

<!ELEMENT prize (#PCDATA)>
<!ATTLIST prize nickname (none|gold|silver|blonze|seeded) "none">

<!ELEMENT piano (#PCDATA | cr:utf8-char)*>
<!ATTLIST piano xml:lang CDATA #IMPLIED>

<!ELEMENT score-note (#PCDATA)>

<!ELEMENT p:translated-by (#PCDATA | cr:utf8-char)*>
<!ATTLIST p:translated-by xml:lang CDATA #IMPLIED>

<!ELEMENT notices (notice+)>

<!ELEMENT total-score (#PCDATA)>

<!ELEMENT free-program ((pieceRef | (p:piece | p:suite)?), programNote?)>

<!ELEMENT choir (choir-name, prefecture?, choir-type?, number-of-members?, (piano | accompaniment | conductor)*, prize, special-prize*, program?, scores?, choir-note?)>
<!ATTLIST choir representative (false|true) "false">
<!ATTLIST choir seed (false|true) "false">
<!ATTLIST choir playing-order CDATA #IMPLIED>

<!ELEMENT section-name (#PCDATA | cr:utf8-char)*>
<!ATTLIST section-name date CDATA #IMPLIED>

<!ELEMENT p:arranged-by (#PCDATA | cr:utf8-char)*>
<!ATTLIST p:arranged-by xml:lang CDATA #IMPLIED>

<!ELEMENT choir-type (#PCDATA)>

<!ELEMENT p:mainTitle (#PCDATA | cr:utf8-char)*>

<!ELEMENT result (date*, startTime?, hall?, referee*, reporter+, notices?, section+)>
<!ATTLIST result output CDATA #REQUIRED>

<!ELEMENT section (section-name, choir+)>

<!ELEMENT scores (score+, total-score, score-note)>

<!ELEMENT notice (#PCDATA | cr:utf8-char)*>

<!ELEMENT cvs-id (#PCDATA)>

<!ELEMENT conductor (#PCDATA | cr:utf8-char)*>
<!ATTLIST conductor xml:lang CDATA #IMPLIED>
<!ATTLIST conductor instrument CDATA #IMPLIED>

<!ELEMENT p:titlePrefix (#PCDATA | cr:utf8-char)*>

<!ELEMENT special-prize (#PCDATA)>

<!ELEMENT competition-name (#PCDATA | cr:utf8-char)*>
<!ATTLIST competition-name pref (false|true) "false">
<!ATTLIST competition-name area (false|true) "false">

<!ELEMENT p:piece (p:originated-from?, p:words-by?, p:translated-by?, p:composed-by?, p:arranged-by?, p:title+, p:piece-note?)>

<!ELEMENT choir-name (#PCDATA | cr:utf8-char)*>
<!ATTLIST choir-name xml:lang CDATA #IMPLIED>
<!ATTLIST choir-name url CDATA #IMPLIED>

<!ELEMENT cr:utf8-char (#PCDATA)>
<!ATTLIST cr:utf8-char nickname (none|aacute|Aacute|acirc|Acirc|agrave|Agrave|aring|Aring|atilde|Atilde|auml|Auml|aelig|AElig|ccedil|Ccedil|eth|ETH|eacute|Eacute|ecirc|Ecirc|egrave|Egrave|euml|Euml|iacute|Iacute|icirc|Icirc|igrave|Igrave|iuml|Iuml|ntilde|Ntilde|oacute|Oacute|ocirc|Ocirc|ograve|Ograve|oslash|Oslash|otilde|Otilde|ouml|Ouml|szlig|thorn|THORN|uacute|Uacute|ucirc|Ucirc|ugrave|Ugrave|uuml|Uuml|yacute|Yacute|yuml|abreve|Abreve|amacr|Amacr|aogon|Aogon|cacute|Cacute|ccaron|Ccaron|ccirc|Ccirc|cdot|Cdot|dcaron|Dcaron|dstrok|Dstrok|ecaron|Ecaron|edot|Edot|emacr|Emacr|eogon|Eogon|gacute|gbreve|Gbreve|Gcedil|gcirc|Gcirc|gdot|Gdot|hcirc|Hcirc|hstrok|Hstrok|Idot|Imacr|imacr|ijlig|IJlig|inodot|iogon|Iogon|itilde|Itilde|jcirc|Jcirc|kcedil|Kcedil|kgreen|lacute|Lacute|lcaron|Lcaron|lcedil|Lcedil|lmidot|Lmidot|lstrok|Lstrok|nacute|Nacute|eng|ENG|napos|ncaron|Ncaron|ncedil|Ncedil|odblac|Odblac|Omacr|omacr|oelig|OElig|racute|Racute|rcaron|Rcaron|rcedil|Rcedil|sacute|Sacute|scaron|Scaron|scedil|Scedil|scirc|Scirc|tcaron|Tcaron|tcedil|Tcedil|tstrok|Tstrok|ubreve|Ubreve|udblac|Udblac|umacr|Umacr|uogon|Uogon|uring|Uring|utilde|Utilde|wcirc|Wcirc|ycirc|Ycirc|Yuml|zacute|Zacute|zcaron|Zcaron|zdot|Zdot|acy|Acy|bcy|Bcy|vcy|Vcy|gcy|Gcy|dcy|Dcy|iecy|IEcy|iocy|IOcy|zhcy|ZHcy|zcy|Zcy|icy|Icy|jcy|Jcy|kcy|Kcy|lcy|Lcy|mcy|Mcy|ncy|Ncy|ocy|Ocy|pcy|Pcy|rcy|Rcy|scy|Scy|tcy|Tcy|ucy|Ucy|fcy|Fcy|khcy|KHcy|tscy|TScy|chcy|CHcy|shcy|SHcy|shchcy|SHCHcy|hardcy|HARDcy|ycy|Ycy|softcy|SOFTcy|ecy|Ecy|yucy|YUcy|yacy|YAcy|numero|djcy|DJcy|gjcy|GJcy|jukcy|Jukcy|dscy|DScy|iukcy|Iukcy|yicy|YIcy|jsercy|Jsercy|ljcy|LJcy|njcy|NJcy|tshcy|TSHcy|kjcy|KJcy|ubrcy|Ubrcy|dzcy|DZcy|romanI|romanII|romanIII|romanIV|romanV|romanVI|romanVII|romanVIII|romanIX|romanX|romanXI|romanXII|romanL|romanC|romanD|romanM|romani|romanii|romaniii|romaniv|romanv|romanvi|romanvii|romanviii|romanix|romanx|romanxi|romanxii|romanl|romanc|romand|romanm|maru1|maru2|maru3|maru4|maru5|maru6|maru7|maru8|maru9|maru10|maru11|maru12|maru13|maru14|maru15|maru16|maru17|maru18|maru19|maru20) "none">
<!ATTLIST cr:utf8-char codepoint CDATA #IMPLIED>

<!ELEMENT p:titleSuffix (#PCDATA | cr:utf8-char)*>

<!ELEMENT given-program ((pieceRef | (p:piece | p:suite)?), programNote?)>

<!ELEMENT p:suite (p:originated-from?, p:words-by?, p:translated-by?, p:composed-by?, p:arranged-by?, p:title+, p:suite-piece+, p:piece-note?)>

<!ELEMENT programNote (#PCDATA)>

<!ELEMENT p:piece-number (#PCDATA | cr:utf8-char)*>

<!ELEMENT choir-note (#PCDATA)>

<!ELEMENT reporter-email (#PCDATA)>
<!ATTLIST reporter-email anonymous (false|true) "false">

<!ELEMENT referee (#PCDATA | cr:utf8-char)*>
<!ATTLIST referee xml:lang CDATA #IMPLIED>
<!ATTLIST referee shortname CDATA #REQUIRED>
<!ATTLIST referee job CDATA #IMPLIED>
<!ATTLIST referee referred-date CDATA #IMPLIED>
<!ATTLIST referee country CDATA #IMPLIED>

<!ELEMENT p:words-by (#PCDATA | cr:utf8-char)*>
<!ATTLIST p:words-by xml:lang CDATA #IMPLIED>
<!ATTLIST p:words-by kind CDATA #IMPLIED>

<!ELEMENT reporter (reporter-name, reporter-email)>
<!ATTLIST reporter anonymous (false|true) "false">

<!ELEMENT p:composed-by (#PCDATA | cr:utf8-char)*>
<!ATTLIST p:composed-by xml:lang CDATA #IMPLIED>

<!ELEMENT prefecture (#PCDATA)>

<!ELEMENT p:title (p:titlePrefix?, p:mainTitle, p:titleSuffix?)>
<!ATTLIST p:title original (true|false) "true">
<!ATTLIST p:title xml:lang CDATA #IMPLIED>

<!ELEMENT number-of-members (#PCDATA)>

<!ELEMENT date (#PCDATA)>
<!ATTLIST date day-of-week (sun|mon|tue|wed|thu|fri|sat) "sun">
<!ATTLIST date holiday (false|true) "false">

<!ELEMENT p:suite-piece (p:piece | p:suite | p:piece-number)+>

<!ELEMENT competition (cvs-id, competition-name, result+)>
<!ATTLIST competition xml:lang CDATA #IMPLIED>

<!ELEMENT pieceRef EMPTY>
<!ATTLIST pieceRef number (G1|G2|G3|G4|M1|M2|M3|M4|F1|F2|F3|F4) "G1">
<!ATTLIST pieceRef href CDATA #REQUIRED>

<!ELEMENT p:piece-note (#PCDATA | cr:utf8-char)*>
<!-- $Id: jca-comp-result.dtd,v 1.2 2002/08/26 07:26:36 kunishi Exp $ -->
<!ATTLIST competition xmlns CDATA #FIXED "http://www.chorusroom.org/xml">
<!ATTLIST competition xmlns:p CDATA #FIXED "http://www.chorusroom.org/piece">
<!ATTLIST competition xmlns:cr CDATA #FIXED "http://www.chorusroom.org/character">

=== kunishi/chorusroom-cms/db/concours/JCA/51st/shizuoka.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE competition PUBLIC "-//CHORUSROOM//DTD Contest JCA 1.0//JA" "http://localhost/DTD/jca-comp-result.dtd">
<competition xmlns:cr="http://www.chorusroom.org/character" xmlns:p="http://www.chorusroom.org/piece" xmlns="http://www.chorusroom.org/xml">
<cvs-id>$Id: shizuoka.xml,v 1.13 2002/06/18 15:21:36 kunishi Exp $</cvs-id>
<competition-name pref="true" area="false">第51回全日本合唱コンクール静岡県大会</competition-name>
<result output="shizuoka">
<date day-of-week="sun" holiday="false">1998-09-13</date>
<reporter anonymous="false">
<reporter-name>早川徳次</reporter-name>
<reporter-email anonymous="false">tokuji@emi.yamaha.co.jp</reporter-email>
</reporter>
<notices>
<notice>同一賞内は出演順です。金賞受賞団体が関東支部大会に出場いたします。</notice>
</notices>
<section>
<section-name>一般の部</section-name>
<choir representative="true" seed="false">
<choir-name>静岡合唱団</choir-name>
<choir-type>mixed</choir-type>
<number-of-members>38</number-of-members>
<prize nickname="gold">金賞</prize>
<program>
<given-program>
<pieceRef number="G1" href="givenPrograms-51st.xml"/>
</given-program>
<free-program>
<p:suite>
<p:composed-by>三善晃</p:composed-by>
<p:title original="true" xml:lang="ja">
<p:mainTitle>嫁ぐ娘に</p:mainTitle>
</p:title>
<p:suite-piece>
<p:piece>
<p:title original="true" xml:lang="ja">
<p:mainTitle>戦いの日々</p:mainTitle>
</p:title>
</p:piece>
</p:suite-piece>
<p:suite-piece>
<p:piece>
<p:title original="true" xml:lang="ja">
<p:mainTitle>かどで</p:mainTitle>
</p:title>
</p:piece>
</p:suite-piece>
</p:suite>
</free-program>
</program>
</choir>
<choir representative="true" seed="false">
<choir-name>アルス・アンティカ</choir-name>
<choir-type>mixed</choir-type>
<number-of-members>18</number-of-members>
<prize nickname="gold">金賞</prize>
<program>
<given-program>
<pieceRef number="G1" href="givenPrograms-51st.xml"/>
</given-program>
<free-program>
<p:suite>
<p:composed-by>Victoria</p:composed-by>
<p:title original="true">
<p:mainTitle>Missa Pro Defunctis</p:mainTitle>
</p:title>
<p:suite-piece>
<p:piece>
<p:title original="true">
<p:mainTitle>Kyrie</p:mainTitle>
</p:title>
</p:piece>
</p:suite-piece>
</p:suite>
</free-program>
<free-program>
<p:piece>
<p:composed-by>Pilkington</p:composed-by>
<p:title original="true">
<p:mainTitle>The Messenger Of Spring</p:mainTitle>
</p:title>
</p:piece>
</free-program>
</program>
</choir>
<choir representative="true" seed="false">
<choir-name>浜松合唱団</choir-name>
<choir-type>mixed</choir-type>
<number-of-members>45</number-of-members>
<prize nickname="gold">金賞</prize>
<special-prize>全日本合唱連盟理事長賞</special-prize>
<program>
<given-program>
<pieceRef number="G4" href="givenPrograms-51st.xml"/>
</given-program>
<free-program>
<p:piece>
<p:composed-by>J. Karai</p:composed-by>
<p:title original="true">
<p:mainTitle>Stabat Mater</p:mainTitle>
</p:title>
</p:piece>
</free-program>
</program>
</choir>
<choir representative="false" seed="false">
<choir-name>浜松フラウエンコール</choir-name>
<choir-type>female</choir-type>
<number-of-members>28</number-of-members>
<prize nickname="silver">銀賞</prize>
<program>
<given-program>
<pieceRef number="F3" href="givenPrograms-51st.xml"/>
</given-program>
<free-program>
<p:piece>
<p:composed-by>A. Heiler</p:composed-by>
<p:title original="true">
<p:mainTitle>Kyrie</p:mainTitle>
</p:title>
</p:piece>
</free-program>
<free-program>
<p:piece>
<p:composed-by>A. Heiler</p:composed-by>
<p:title original="true">
<p:mainTitle>Gloria</p:mainTitle>
</p:title>
</p:piece>
</free-program>
</program>
</choir>
<choir representative="false" seed="false">
<choir-name>VOX POPULI</choir-name>
<choir-type>mixed</choir-type>
<number-of-members>18</number-of-members>
<prize nickname="silver">銀賞</prize>
<program>
<given-program>
<pieceRef number="G1" href="givenPrograms-51st.xml"/>
</given-program>
<free-program>
<p:suite>
<p:composed-by>A. Copland</p:composed-by>
<p:title original="true">
<p:mainTitle>Four Motets</p:mainTitle>
</p:title>
<p:suite-piece>
<p:piece>
<p:title original="true">
<p:mainTitle>Help Us Lord</p:mainTitle>
</p:title>
</p:piece>
</p:suite-piece>
<p:suite-piece>
<p:piece>
<p:title original="true">
<p:mainTitle>Thou O Jehovah</p:mainTitle>
</p:title>
</p:piece>
</p:suite-piece>
<p:suite-piece>
<p:piece>
<p:title original="true">
<p:mainTitle>Abideth Forever</p:mainTitle>
</p:title>
</p:piece>
</p:suite-piece>
</p:suite>
</free-program>
</program>
</choir>
<choir representative="false" seed="false">
<choir-name>キンダーコーア花輝</choir-name>
<choir-type>children</choir-type>
<number-of-members>15</number-of-members>
<prize nickname="blonze">銅賞</prize>
<program>
<given-program>
<pieceRef number="F2" href="givenPrograms-51st.xml"/>
</given-program>
<free-program>
<p:suite>
<p:composed-by>Ziegler</p:composed-by>
<p:title original="true" xml:lang="ja">
<p:mainTitle>大地への祈り</p:mainTitle>
</p:title>
<p:suite-piece>
<p:piece>
<p:title original="true">
<p:mainTitle>Alleluja</p:mainTitle>
</p:title>
</p:piece>
</p:suite-piece>
<p:suite-piece>
<p:piece>
<p:title original="true">
<p:mainTitle>Kyrie</p:mainTitle>
</p:title>
</p:piece>
</p:suite-piece>
<p:suite-piece>
<p:piece>
<p:title original="true">
<p:mainTitle>Gloria</p:mainTitle>
</p:title>
</p:piece>
</p:suite-piece>
<p:suite-piece>
<p:piece>
<p:title original="true">
<p:mainTitle>Agnus Dei</p:mainTitle>
</p:title>
</p:piece>
</p:suite-piece>
</p:suite>
</free-program>
</program>
</choir>
</section>
<section>
<section-name>職場の部</section-name>
<choir representative="true" seed="false">
<choir-name>YAMAHA Chamber Choir</choir-name>
<choir-type>male</choir-type>
<number-of-members>12</number-of-members>
<prize nickname="gold">金賞</prize>
<program>
<given-program>
<pieceRef number="M1" href="givenPrograms-51st.xml"/>
</given-program>
<free-program>
<p:suite>
<p:composed-by>Gustafson</p:composed-by>
<p:title original="true">
<p:mainTitle>Missa a capella</p:mainTitle>
</p:title>
<p:suite-piece>
<p:piece>
<p:title original="true">
<p:mainTitle>Kyrie</p:mainTitle>
</p:title>
</p:piece>
</p:suite-piece>
<p:suite-piece>
<p:piece>
<p:title original="true">
<p:mainTitle>Gloria</p:mainTitle>
</p:title>
</p:piece>
</p:suite-piece>
<p:suite-piece>
<p:piece>
<p:title original="true">
<p:mainTitle>Agnus Dei</p:mainTitle>
</p:title>
</p:piece>
</p:suite-piece>
</p:suite>
</free-program>
</program>
</choir>
<section-name>大学の部</section-name>
<choir representative="true" seed="false">
<choir-name>静岡大学</choir-name>
<choir-type>mixed</choir-type>
<number-of-members>59</number-of-members>
<prize nickname="seeded">シード</prize>
<program>
<given-program>
<pieceRef number="G1" href="givenPrograms-51st.xml"/>
</given-program>
<free-program>
<p:suite>
<p:composed-by>三善晃</p:composed-by>
<p:title original="true" xml:lang="ja">
<p:mainTitle>嫁ぐ娘に</p:mainTitle>
</p:title>
<p:suite-piece>
<p:piece>
<p:title original="true" xml:lang="ja">
<p:mainTitle>あなたのうまれたのは</p:mainTitle>
</p:title>
</p:piece>
</p:suite-piece>
<p:suite-piece>
<p:piece>
<p:title original="true" xml:lang="ja">
<p:mainTitle>かどで</p:mainTitle>
</p:title>
</p:piece>
</p:suite-piece>
</p:suite>
</free-program>
</program>
</choir>
</section>
</result>
</competition>
